### PR TITLE
Fix indentation and add a missing `let`

### PR DESCRIPTION
**Pull request by yuvallanger**

### CODE REVIEW

**Comment by polarina** [comment]
That `let` is not necessary for successful compilation. Am I missing something?

**Comment by tejon** [comment]
It's a documentation example code fragment, so it isn't compiling to begin with. It's correct as written (including the indentation) because `let` creates a block which allows multiple bindings. This change is not strictly incorrect, since this example is a `do` block and `in` is optional; but it's definitely unnecessary, and and it *would* break a pure function, making it poor idiom IMO.

**Comment by yuvallanger** [comment]
I am using tab indentation in my source and apparently it only breaks in my case. Sorry about that.

**Comment by polarina** [comment]
@yuvallanger: what I do to avoid similar situations is have my text editor render tab and space characters in a visually distinguishable manner. Gedit, for example, ships by default a "Draw Spaces" plugin that you can take a look at.

**Pull request closed without merging**
