### PR TITLE
allow low-level access to buffer in audio callback

### PR DESCRIPTION
**Pull request by svenkeidel**
The problem with the current type of the audio callback `(CInt -> IO (Vector Word8))`
is that it enforces to allocate a new chunk of memory in every call of the
callback. Audio synthesis is very performance sensitive and every unnecessary
allocation can cause stuttering and hang ups of the audio signal, which is
unacceptable.

I propose to use the type of the low-level SDL Audio API `(Ptr Word8 -> CInt -> IO ())`
which omits allocations. For people who liked the old API, we could offer a
conversion function that converts the high-level callback to the low-level:
`(CInt -> IO (Vector Word8)) -> (Ptr Word8 -> CInt -> IO ())`

### CODE REVIEW

**Comment by ocharles** [comment]
What about an MVector, I wonder if that would be nicer? I'm also tempted to
somehow have the MVector elements somehow tied to the AudioFormat, perhaps
as a phantom type.

**Comment by svenkeidel** [comment]
Choosing `Vector` or `MVector` enforces an abstraction on users that they may not want. I for my part use some auxiliary c functions that efficiently transfer audio data into the output buffer and deal with endian conversion. Other users may use other datatypes for their audio data like infinite streams or even SSE registers. Converting these datatypes in vectors that than get copied to memory anyway feels awkward and may not be needed. In my opinion using the lowest common denominator (the raw chunk of memory) is a good choice in this case.

**Comment by ocharles** [comment]
You are right, but that's also kind of the point! `SDL` is meant to be opinionated, but provide an escape hatch if you want to go over to `SDL.Raw` to really manipulate pointers. @polarina, what do you think? (delegation ftw)

**Comment by polarina** [comment]
I agree with @ocharles. `SDL` is opinionated, it is the only reasonable way to get anything high-level done (which is also why people fight over Python vs. Ruby).

I am of course willing to consider all options that can improve efficiency as long as users aren't exposed to any low-level shenanigans.

**Comment by svenkeidel** [comment]
Ok, maybe it is better to discuss this issue with some concrete examples: https://gist.github.com/svenkeidel/6cd67843e96ca7682e6c

I prepared two files that use an infinite stream, one file that uses the old type and one that uses the new type.

The "Vector" solution certainly looks nicer, but it has several problems:
 * It creates a lots of intermediate lists due to little endian conversion.
 * A new vector gets allocated in every call


The "Ptr" solution lacks in elegance, but:
 * It doesn't have to deal with endian conversion, it simply uses the `Ptr Word8` as an `Ptr Word32` array.
 * It runs in constant memory (assuming SDL does not allocate new memory in every call to the callback).

**Comment by svenkeidel** [comment]
So, what is the decision on this one?

**Comment by ocharles** [comment]
The decision is that this is still undecided :) Not a great response, sorry!

**Comment by svenkeidel** [comment]
How can I do to convince you, that the one solution is better than the other? Write some benchmarks maybe?

**Comment by ocharles** [comment]
It's less a case of convincing and more a case of me finding time to think about this. I haven't had chance to do that yet.

**Comment by Noeda** [comment]
How about this:

Keep the high-level module as is it now. But write in the module haddocks what to use from the raw package/modules if the user needs the performance and how it will be safe with the high-level bindings.

The point of the documentation would be that interaction between the high-level and low-level code is now well defined; the user will not need to be afraid of breaking something in the high-level bindings if they decide they need to go low-level.

High-level bindings lose much of their value if performance is unacceptable.

**Comment by ocharles** [comment]
Haven't forgotten about this, hoping to revisit tonight

**Comment by ocharles** [comment]
@svenkeidel I explored the `MVector` approach and I am quite happy with how it came out. You can review it at https://github.com/haskell-game/sdl2/tree/mvector-audio. How do you feel about this approach? There is an example similar to the one you gave here, see `AudioExample.hs` in that branch.

**Comment by ocharles** [comment]
Closing as `mvector-audio` is now merged.

**Comment by svenkeidel** [comment]
I'm sorry for not responding, I'm very busy myself. I think MVector is a great choice. It gives you low level access and avoids unnecessary allocations.

Best,
Sven

**Comment by ocharles** [comment]
Phew! :)

**Pull request closed without merging**
