### PR TITLE
SDL.Event.pollEvents: remove redundant constraint

### PR DESCRIPTION
**Pull request by endgame**
MonadIO m => Monad m => Applicative m => Functor m

### CODE REVIEW

**Comment by ocharles** [comment]
While true now, I need to check if this holds on older GHCs

**Comment by endgame** [comment]
Looking at hackage docs, it's true as far back as base-4.9.0.0 at least.

**Comment by endgame** [comment]
This is still relevant. Are there any more checks you'd like to see?

**Comment by ocharles** [comment]
No, thank you for the nudge - I'm holiday today but when I'm back tomorrow I'll try and take a look in the week. Thanks!

**Comment by ocharles** [comment]
Thanks!

**Pull request merged**
