### PR TITLE
 ChangeLog formatting; improve documentation about windowSize and windowHighDPI.

### PR DESCRIPTION
**Pull request by nickkuk**
See #172 and #140.

### CODE REVIEW

**Comment by chrisdone** [comment]
> I've added some documentation. I didn't write about SDL.get (SDL.rendererViewport renderer), because this variable changes over time. You can be sure that it will return what you need only in a moment after window creation, or after SDL.rendererViewport renderer $= Nothing. 

That's reasonable. 

This PR looks good then! I wasn't aware that `glGetDrawableSize` was already available in the high-level binding. 👏

**Comment by chrisdone** [comment]
That seems like a good number of mentions of `glGetDrawableSize` to give people the hint that this is important.

**Comment by chrisdone** [comment]
Thanks @nickkuk :metal:

**Comment by ocharles** [comment]
Agreed, looks great. Thankoo! 😍

**Pull request merged**
