### PR TITLE
export toNumber and fromNumber instances

### PR DESCRIPTION
**Pull request by nek0**
I needed to handle some raw values from sdl, but was not able to use them properly without these exports. Is it possible to put that upstream?
Thanks.

### CODE REVIEW

**Comment by ocharles** [comment]
I wouldn't want to add it to the `SDL` export list, but I'd be happy just exposing that whole internal module. Could you add it to exported-modules in the cabal file?

**Comment by nek0** [comment]
Is moved. Thanks.

**Comment by ocharles** [comment]
Thanks, but now you need to remove it from `other-modules`, as indicated by the Travis build failure above.

**Comment by nek0** [comment]
done. Sorry I missed that.

**Comment by ocharles** [comment]
Perfect, thank you!

**Pull request merged**
