### PR TITLE
Clipboard text is not a valid Vulkan driver

### PR DESCRIPTION
**Pull request by expipiplus1**
!

### CODE REVIEW

**Comment by ocharles** [comment]
Wow... what on earth happened there?!

**Comment by expipiplus1** [comment]
Yeah, I guess this has never been used until now :/

**Comment by expipiplus1** [comment]
Is it possible to get a Hackage release with this fix in, please?

**Comment by ocharles** [comment]
Yes, let me see if I can cut one now.

**Comment by ocharles** [comment]
Released as 2.5.2.0.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by expipiplus1** [comment]
Technically a breaking change for those relying on the old behaviour!

**Comment by ocharles** [comment]
Yea I wasn't entirely sure what to do, but I have a hard time believing anyone would have used this and not either complained or deleted it. Given the cost of major bumps, I decided to go with a minor bump here

**Pull request merged**
