### PR TITLE
add palette* related functions

### PR DESCRIPTION
**Pull request by rueshyna**
I added palette* related functions which can help to perform pixel level operation 

reference : https://wiki.libsdl.org/SDL_PixelFormat#Code_Examples

### CODE REVIEW

**Comment by polarina** [comment]
What are the use cases for `palleteNColors` and `palleteColor`?

**Comment by rueshyna** [comment]
`paletteNColors` is for getting number of colors in palette.
`paletteColor` is for getting RGBA value while given specific index.

You can see the first example of `https://wiki.libsdl.org/SDL_PixelFormat`

I'm preparing to develop some kind of painting tool so pixel information is useful.

**Comment by rueshyna** [comment]
@ocharles I hid `mapM` of `Data.Traversable` to fix build failure.

**Comment by rueshyna** [comment]
hmm.. CI build still failed. 
But it works on my dev box.
Is it possible to upgrade ghc to `8.0.2` or use newer base(>=4.9) ?

**Comment by ocharles** [comment]
I think you *want* that version of `mapM`. You could also try using `for` or `traverse`

**Comment by rueshyna** [comment]
@ocharles after changed to `traverse`, it works!

**Comment by ocharles** [comment]
Thanks for your contribution!

**Pull request merged**
