### PR TITLE
added relative mouse movement function to high level API

### PR DESCRIPTION
**Pull request by Velro**
It might be good to have this throw some error or warning if relativeMouseMode isn't on, and then also have a warning for when getMouseLocation is called, but relativeMouseMode is on. I'm not sure how that should be handled.

### CODE REVIEW

**Comment by polarina** [comment]
@ocharles, @Velro: would it make sense to have `getMouseLocation` call either `Raw.getMouseState` or `Raw.getRelativeMouseState` depending on the current relative mouse mode?

**Comment by tejon** [comment]
@polarina That does smell an awful lot like global state... but then, having each function return `Maybe` or `Either` just forces the user to perform that same check. If there's no way around it, the lesser evil is for the library to handle it.

**Comment by afwlehmann** [comment]
@tejon: But then the user should know which mode they are using and for sake of speed (and sanity ;-)) we should avoid both global state and performing the corresponding checks internally every single time the function is called. Returning `Maybe` or `Either` also seems to much too me, as a failure rather hints at a programming error than at a function that supposedly can or cannot return a value.

**Comment by Velro** [comment]
I'll elaborate on the behavior. When the incorrect location/state call is made, the correct values are still returned. The RelativeMouseMode seems to only affect cursor behavior. However, these cursor modes and location calls go hand in hand.
``` Haskell
relativeMouseMode False --Cursor is visible and can exit window
relativeMouseMode True  --Cursor is invisible and can't exit window
```
Perhaps we can leave it with no warning or Maybe/Either, and add what I described above to the documentation? Or maybe we could rename get/setRelativeMouseMode to something else.

Here is the [original documentation on SetRelativeMouseMode](https://wiki.libsdl.org/SDL_SetRelativeMouseMode?highlight=%28\bCategoryMouse\b%29|%28CategoryEnum%29|%28CategoryStruct%29)

**Comment by tejon** [comment]
@afwlehmann If speed is an issue when checking mouse position, there's probably a bigger problem. ;) Fair argument that requiring the user to keep state in their head is not great either, tho. Are you advocating throwing an exception?

**Comment by afwlehmann** [comment]
@tejon You're right :) Although I'm not a big fan of exceptions, this is a place where I would exceptionally ;-) consider throwing one.

**Comment by tejon** [comment]
@Velro Does the cursor still move normally when in relative mode, or does SDL_GetMouseState always return a value corresponding to window center (or delta from it since last frame)? Can't test it myself right now, but I expect the latter -- which amounts to silently breaking so far as useful information is concerned.

**Comment by Velro** [comment]
@tejon In the case of 
```Haskell
SDL.setRelativeMouseMode True
mouseCoord <- SDL.getMouseLocation
```
I get coordinates ranging from (0,0) to (screenWidth, screenHeight). But I cannot see the cursor so its not too useful. Does that answer your question?

**Comment by tejon** [comment]
@Velro Not entirely -- the important part is, once the mouse is at any arbitrary location, does it stay there next frame if you don't move it yourself? Relative modes often force the mouse to window-center after sampling the delta, for a fixed reference point.

If SDL *doesn't* work that way, and the return values are consistent between modes -- i.e., one can use `getMouseLocation` to render a custom cursor while in relative mode, and also can use `getRelativeMouseLocation` to rotate a 3D view while in non-relative mode, with everything working as expected -- then there's really no problem.

But if one of those functions doesn't have the expected behavior if you're accidentally in the wrong mode, I think that needs to be handled at the API level.

**Comment by tejon** [comment]
In the latter case, I'm torn between:

    data MouseLocation a = Absolute a | Relative a
    getMouseLocation :: MonadIO m => m (MouseLocation (Point V2 CInt))

vs.

    data LocationMode = Absolute | Relative
    getMouseLocation :: MonadIO m => m (LocationMode, Point V2 CInt)
    (Also change set/getRelativeMouseMode to use LocationMode?)

Pretty sure the former is cheaper, but the latter lets you use `snd` or `(_, pos)` instead of forcing a verbose pattern match every time.

**Comment by Velro** [comment]
Someone could use getMouseLocation to render a custom cursor while in relative mode. Someone couldn't really rotate a 3D view effectively in absolute mode if the application is windowed, as it always returns no motion (0,0) if the cursor is moved outside of the SDL window.

**Comment by afwlehmann** [comment]
@tejon ...and I agree with you. Now that I see it I'd actually go with your proposal. Thinking about usages, I'd then go for the second version.

**Comment by tejon** [comment]
So, it sounds like the output in the "wrong" mode is still usable in both cases -- slightly less so for Relative, but I can still see potential use cases. It seems reasonable to provide both functions unchecked (without the user having to resort to raw calls). The checked-with-tuple version also seems useful, but with the unchecked functions it's trivial to implement, so the question boils down to whether or not it's worth expanding the API footprint for it.

Either way, I'd like to see the `LocationMode` data type used for `[g|s]etMouseLocationMode`, replacing `[g|s]etRelativeMouseMode`. Even if the checked function is still left up to the user, this at least gives a canonical way to avoid Boolean blindness.

**Comment by ocharles** [comment]
I don't think I like having `getMouseLocation` change depending on some other global state. If we introduce `getRelativeMouseLocation`, I think `getMouseLocation` should be deprecated and renamed as `getAbsoluteMouseLocation`. That, or what @tejon is suggesting which (if I understand correctly) is a single function that requires a value that indicates which type of location to fetch.

**Comment by tejon** [comment]
My suggestion was to have `getMouseLocation` *return* a value indicating which state it's in. `getRelativeMouseLocation` and `getAbsoluteMouseLocation` would also be available -- I wasn't explicit about naming, but I did envision having all three of those functions.

**Comment by ocharles** [comment]
Ah, I see!

:+1:, I like the sound of this.

**Comment by tejon** [comment]
OK, so relative to this pull request, the suggestions are:

- rename current `getMouseLocation` to `getAbsoluteMouseLocation`
- remove `getRelativeMouseMode` and `setRelativeMouseMode`
- add the following:

    data LocationMode = Absolute | Relative

    setMouseLocationMode :: (Functor m, MonadIO m) => LocationMode -> m ()
    setMouseLocationMode mode =
      throwIfNeg_ "SDL.Input.Mouse" "SDL_SetRelativeMouseMode"
        . Raw.setRelativeMouseMode $ case mode of
          Relative -> True
          _ -> False

    getMouseLocationMode :: MonadIO m => m LocationMode
    getMouseLocationMode = do
      relative <- Raw.getRelativeMouseMode
      pure $ if relative then Relative else Absolute

    getMouseLocation :: MonadIO m => m (LocationMode, Point V2 CInt)
    getMouseLocation = do
      mode <- getMouseLocationMode
      location <- case mode of
        Relative -> getRelativeMouseLocation
        _ -> getAbsoluteMouseLocation
      pure (mode, location)

(Note: if the above compiles, it's dumb luck.)

**Comment by tejon** [comment]
On further consideration, I'm not sure I like that throw. Why should this blow up when there's a perfectly good mechanism for reporting failure? This is absolutely not performance-critical code. I'd prefer the following:

    setMouseLocationMode :: (Functor m, MonadIO m) => LocationMode -> m LocationMode
    setMouseLocationMode mode = do
      Raw.setRelativeMouseMode (mode == relative)
      getMouseLocationMode

**Comment by Velro** [comment]
Okay I will update with your suggestion tonight @tejon.

**Comment by Velro** [comment]
Okay I've updated as you specified @tejon. I had to switch Relative/Absolute to RelativeLocation/AbsoluteLocation due to a name clash in Video.hs. @ocharles I'm not sure if you would prefer straight API changes, or to have more of a "deprecated next version, removed version after that" kind of approach. If the latter, I'm not really sure how you want to do warnings.

**Comment by ocharles** [comment]
I certainly want to avoid breaking the API with no deprecation period, unless absolutely essential. I'll have a look and see if there is anything that can be done to avoid breaking peoples code.

**Comment by tejon** [comment]
The only sticky point is that we want to repurpose the name `getMouseLocation`. Everything else is already deprecation-friendly. For now, why don't we rename the new function to `getModalMouseLocation`, which allows `getMouseLocation = getAbsoluteMouseLocation` for the deprecation cycle, at which point it can switch to `getMouseLocation = getModalMouseLocation` for another cycle to deprecate the latter. (Or if someone can come up with a better new name, we can just use that and skip part 2.)

**Comment by Velro** [comment]
Reintroduced old functions as deprecated and renamed to getModalMouseLocation. Sorry if this comment isn't necessary, not sure if you guys get notified when a commit is made here.

I haven't seen deprecation in other packages so here's an example of the exact verbiage ghc spits out on compile when using a deprecated function.

```
ParticleDemo.hs:127:3: Warning:
    In the use of ‘SDL.setRelativeMouseMode’
    (imported from SDL, but defined in SDL.Input.Mouse):
    Deprecated: "Use getMouseLocationMode instead"
```

**Comment by tejon** [comment]
I'd change the deprecation text for `getMouseLocation` to simply: `"Use getAbsoluteMouseLocation instead."`, and change its definition to `getMouseLocation = getAbsoluteMouseLocation` so there's no confusion for source code browsers.

I'm not sure where, or whether, a note should be added mentioning that this is part 1 of a two-stage process. Other than that, I think I'm happy with it. @ocharles @polarina ?

**Comment by Velro** [comment]
Added @tejon suggestions. Sorry for the delay, had to move into a new house.

**Comment by ocharles** [comment]
Apologies for letting this languish, I was hoping to have this in `sdl2-2.1.0` but unfortunately haven't had time to re-review (and the current version doesn't build). Can hopefully get this out for `sdl2-2.2.0`.

**Pull request merged**
