### PR TITLE
Add ticks64

### PR DESCRIPTION
**Pull request by dxtr**
This is a wrapper around SDL_GetTicks64

### CODE REVIEW

**Comment by dpwiz** [comment]
> This function is available since SDL 2.0.18.

Should be under the `recent-ish` flag/guard:

```
{-# LANGUAGE CPP #-}

...

#ifdef RECENT_ISH
...
#endif
```

**Comment by dxtr** [comment]
You're too fast! :)

**Comment by dxtr** [comment]
Okay there we go. Tested this with the UserEvent example by replacing `ticks` with `ticks64` and it seems to work.

Sorry about that, I was banking on that it'd take a while for you to get to it

**Comment by dxtr** [comment]
Also, should I use recent-ish for functions added after 2.0.6?

**Comment by dpwiz** [comment]
The `recent-ish` cutoff is 2.0.8, the version in Ubuntu LTS-18.
It should be EOL this year, but apparently Hackage and Stackage are still on it.

**Comment by dxtr** [comment]
Seems the windows builds aren't happy

**Pull request merged**
