### PR TITLE
Adding a Get Started guide

### PR DESCRIPTION
**Pull request by soupi**
This PR adds a short get started guide.

I tried explaining one of the first examples of lazyfoo's guide (example 3) and what the Haskell code is doing, and linked for [an example snake game](/soupi/sdl2-snake) I wrote to complement the guide.

I don't mind moving the example game to a different repository if needed.

Let me know if there's anything you'd like me to change.

Thanks!

### CODE REVIEW

**Comment by soupi** [comment]
You are totally right. I seem to have totally missed this guide :\ (or maybe I saw it a long time ago) and it seems really similar already.
I can remove what i wrote completely and just provide a link straight to that module from the readme if that's alright.

**Comment by ocharles** [comment]
I think that would be best. I'd suggest we

* Add a link to getting started in the `README` (as you did).
* Maybe also mention it in the `sdl2.cabal` "description" section, which is the first block of text you see at http://hackage.haskell.org/package/sdl2.

**Comment by soupi** [comment]
I've made the requested changes and also decided to leave the description for SDL (taken from the `SDL` module) and the link to the other libraries. If you want me to remove that just let me know.

**Comment by ocharles** [comment]
Perfect! This is a definite improvement, thank you for taking the time to contribute! :+1:

**Comment by soupi** [comment]
Thank you all for this awesome library!

**Pull request merged**
