### PR TITLE
Retrieve, create and other stuff for the mouse cursor

### PR DESCRIPTION
**Pull request by afwlehmann**
Some functions for the retrieval, creation and removal of mouse cursors.

### CODE REVIEW

**Comment by afwlehmann** [comment]
Erm, just ran into a merge conflict. I'll solve it and keep you posted.

**Comment by polarina** [comment]
`SDL_CreateCursor` will return `NULL` on failure. You need to check for that and throw an exception if that's the case.

**Comment by afwlehmann** [comment]
Yes, I forgot at first but added it once I realized that. Should be fixed by now.

**Comment by polarina** [comment]
Thanks!

**Pull request merged**
