### PR TITLE
high-level API for SDL_AddEventWatch

### PR DESCRIPTION
**Pull request by matthewleon**
Addresses #144.

Code is based on similar code in `SDL/Time.hs`.

### CODE REVIEW

**Comment by ocharles** [comment]
Looks good! Could you also update the changelog?

**Comment by matthewleon** [comment]
> Could you also update the changelog?

done

**Comment by matthewleon** [comment]
@ocharles any further feedback on this?

**Comment by ocharles** [comment]
No further feedback, thank you so much for your contribution! I've scheduled a release for the next few weeks, as we have a few more PRs open.

**Pull request merged**
