### PR TITLE
Add wrapper for updateTexture

### PR DESCRIPTION
**Pull request by BartAdv**
I'm just not sure if `IOVector` is right for the pixel data here. I used is as it's the one used by `CreateRGBSurfaceFrom` but in that case the underlying memory is shared between surface and the MVector which is not the case for `updateTexture`.

### CODE REVIEW

**Comment by BartAdv** [comment]
Just found out ByteString would be better candidate for pixel data, I will rework it.

**Comment by BartAdv** [comment]
Reworked for `ByteString`. For this, however, I had to use functionality from `Data.ByteString.Internal`.

**Comment by tejon** [comment]
Hey! I'm the new guy, here to hopefully help things happen. :) A couple of comments --

- It looks like you based the signature on `surfaceBlit`. However, that function has the source as the first argument, as opposed to the destination for `updateTexture`. I'm torn on this because I think yours is the better ordering, but consistency is important and breaking changes suck. (I also don't like `Maybe` as a behavior switch, but one battle at a time...)

- Probably worth returning `m Texture` rather than `m ()`, for better composition behavior.

- I kind of want that `BS.ByteString -> CInt ->` wrapped into something like `Raster {source::BS.ByteString, scanlength::CInt}`. In addition to cleaning up the signature here, it seems like if you're using this function it would be handy for managing update sources in general.

**Comment by BartAdv** [comment]
* You're right that there's an incosistency in the target/source parameter ordering, but I merely based the signature on the native counterpart: https://wiki.libsdl.org/SDL_UpdateTexture.

* Returning `m Texture` - the other similar functions (related to surfaces), just return `()` as well...

* Not sure about last point - would it be useful in other places? I don't know the API that much, but pitch itself is used in `createRGBSurfaceFrom` and here existing pixel data is IOVector Word8 (shared memory) instead of `ByteString` which is just used only for creation here.

**Comment by tejon** [comment]
Ha, so the inconsistency goes right to the source... I believe the surface function argument orders are all directly based on the native ones, too. Well, that actually does make _our_ behavior consistent: match the SDL reference. So, no issue there.

I did notice that all our surface functions return `()`, but in this case I think it's worth ignoring that pattern because monadic return values are easy to discard. `_ <- foo`, `mapM_ foo`, etc., etc. If it's not needed, it's not in the way. It seems useful to be able to handle textures in a more functional style -- moreso than for surfaces, though to be honest I'm not 100% sure I agree with returning `()` from those functions either.

For the `Raster` idea, I'm not sure it would be immediately useful outside this function, though the ability to build a set of "update sources" with a nice clean data format does seem handy. But since we're already using the other convention elsewhere, that's probably best saved for a later major revision.

**Comment by BartAdv** [comment]
Changed return type

**Comment by tejon** [comment]
Manually merged to branch `master-next`.

**Pull request closed without merging**
